### ROOT

GET https://konekt-app.herokuapp.com/api/

### REGISTER NEW USER
POST https://konekt-app.herokuapp.com/api/users/register
Content-Type: application/json

{
    "email":"alex67@gmail.com",
    "password":"123456"
}

### LOGIN User
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email":"alex67@gmail.com",
    "password":"blablabla"
}

### GET USER BY USER_ID
GET https://konekt-app.herokuapp.com/api/users/2
Content-Type: application/json

### SEARCH FOR USER
GET http://localhost:3000/api/users/search?q=alex

### Update User Location
PUT http://localhost:3000/api/users/24/location
Content-Type: application/json
# 53.5216312
# -6.0798284

{
    "latitude":53.527302,
    "longitude":-6.095321
}
### Update User Profile -> usernam and/or age
PUT http://localhost:3000/api/users/24/profile
Content-Type: application/json

{
    "username":"alex",
    "age":21
}

### Update User Password
PUT http://localhost:3000/api/users/24/profile/password
Content-Type: application/json

{
    "oldpass":"blablabla",
    "newpass":"blablabla"
}

### Update User Status Message
PUT http://localhost:3000/api/users/24/status
Content-Type: application/json

{
    "statusmsg":"Lunch at 2 anyone?"
}

### Change user's visibility status
PUT http://localhost:3000/api/users/24/visibility


### Delete user
DELETE http://localhost:3000/api/users/13



### GET Distance [metres] between 2 Locations
GET http://localhost:3000/api/checkdistance?lid1=20&lid2=3

### Show User Meetings
GET http://localhost:3000/api/users/24/meetings

### Show User Connections
GET http://localhost:3000/api/users/24/connections

### CREATE New Connection/ Send Connection Request
POST http://localhost:3000/api/users/24/newconnection
Content-Type: application/json

{
    "friend_id":3,
    "discovery_radius":500
}

### ACCEPT Connection Request
POST http://localhost:3000/api/users/3/acceptconnection
Content-Type: application/json

{
    "friend_id":24,
    "discovery_radius":300
}

### Validate User Connection
PUT http://localhost:3000/api/connections/37/validate

### Update connection visibility radius
PUT http://localhost:3000/api/connections/37/visibility
Content-Type: application/json

{
    "radius":1000
}

### Remove user connection
DELETE http://localhost:3000/api/connections/3/


### CREATE new meeting 
POST http://localhost:3000/api/connections/37/meeting?lid=20
Content-Type: application/json

# 1 == connection_id
# lid == location of the user  

### Finish meeting
PUT http://localhost:3000/api/meetings/18/end

### Add special event to a meeting
PUT http://localhost:3000/api/meetings/20/specialevent?sid=2

### Show Current Special Events
GET http://localhost:3000/api/specialevents

### GET Special Event by :spid (special_event_id)
GET http://localhost:3000/api/specialevents/4
